# Generated by Django 6.1.1 on 2026-09-15 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text='e.g. DTCC, NSCC, EUROCLEAR', max_length=20, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClearingMemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=150)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('clearing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to='OperationsClearing.clearinghouse')),
            ],
        ),
        migrations.CreateModel(
            name='MarginRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_margin', models.DecimalField(decimal_places=4, max_digits=18)),
                ('maintenance_margin', models.DecimalField(decimal_places=4, max_digits=18)),
                ('collateral_posted', models.DecimalField(decimal_places=4, max_digits=18)),
                ('margin_call_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('is_margin_call_active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('clearing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_requirements', to='OperationsClearing.clearingmemberaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TradeSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('settlement_type', models.CharField(choices=[('DVP', 'Delivery Versus Payment'), ('FOP', 'Free of Payment'), ('RVP', 'Receive Versus Payment')], default='DVP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Settlement'), ('SETTLED', 'Settled Successfully'), ('FAILED', 'Settlement Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('trade_date', models.DateTimeField()),
                ('settlement_date', models.DateField(db_index=True)),
                ('actual_settlement_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='OperationsClearing.clearingmemberaccount')),
                ('clearing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='OperationsClearing.clearinghouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='SettlementReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('AMOUNT_MISMATCH', 'Amount Mismatch'), ('QUANTITY_MISMATCH', 'Quantity Mismatch'), ('MISSING_INTERNAL', 'Trade Missing Internally'), ('MISSING_CLEARING', 'Trade Missing at Clearing House')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open Discrepancy'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='OperationsClearing.tradesettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
