# Generated by Django 6.1.1 on 2026-09-15 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSurveillanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('WASH_TRADING', 'Wash Trading Detection'), ('FRONT_RUNNING', 'Front Running Detection'), ('LARGE_ORDER', 'Unusually Large Order Volume'), ('PATTERN_DAY_TRADER', 'Pattern Day Trading Limit')], max_length=30)),
                ('description', models.TextField()),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Resource Created'), ('UPDATE', 'Resource Updated'), ('DELETE', 'Resource Deleted'), ('TRADE_EXECUTION', 'Trade Order Executed'), ('LOGIN_ATTEMPT', 'Security Login Event')], max_length=30)),
                ('target_model', models.CharField(help_text='Target entity, e.g. Portfolio', max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Primary key of object', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict, help_text='JSON payload of modifications')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('KYC_VERIFICATION', 'Know Your Customer (KYC)'), ('AML_SCREENING', 'Anti-Money Laundering (AML)'), ('PEP_CHECK', 'Politically Exposed Person (PEP)'), ('SANCTION_LIST', 'Sanctions List Screening')], max_length=30)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FLAGGED', 'Flagged / Suspicious'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Re-check Required')], default='FLAGGED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RestrictedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('reason', models.CharField(choices=[('INSIDER_INFO', 'Insider Knowledge / Material Non-Public Info'), ('REGULATORY_BAN', 'Regulatory Sanction / Ban'), ('CONFLICT_OF_INTEREST', 'Corporate Conflict of Interest')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_restricted_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_account_number', models.CharField(blank=True, help_text='Target portfolio account number', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed narrative of suspicious activity')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Internal Review'), ('REPORTED_TO_AUTHORITIES', 'Reported to Regulatory Authorities'), ('DISMISSED', 'Dismissed / False Positive')], default='UNDER_REVIEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_sars', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
