# Generated by Django 6.1.1 on 2026-09-15 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PortfolioManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('market_shock_pct', models.DecimalField(decimal_places=2, help_text='Broad market shock percentage (e.g., -20.00 for a 20% crash)', max_digits=5)),
                ('interest_rate_change_bps', models.IntegerField(default=0, help_text='Interest rate shift in basis points (e.g., +100 bps)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('MAX_DRAWDOWN', 'Maximum Drawdown (%)'), ('VAR_LIMIT', 'Value at Risk (VaR) Limit ($)'), ('CONCENTRATION', 'Single Asset Concentration (%)'), ('LEVERAGE', 'Maximum Leverage Ratio')], max_length=30)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_limits', to='PortfolioManagement.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'limit_type')},
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_risk_alerts', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='PortfolioManagement.portfolio')),
                ('risk_limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='RiskManagement.risklimit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StressTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected_loss_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('projected_loss_pct', models.DecimalField(decimal_places=4, max_digits=7)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_test_results', to='PortfolioManagement.portfolio')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='RiskManagement.stresstestscenario')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('var_95_daily', models.DecimalField(blank=True, decimal_places=4, help_text='95% Confidence 1-Day Value at Risk ($)', max_digits=18, null=True)),
                ('var_99_daily', models.DecimalField(blank=True, decimal_places=4, help_text='99% Confidence 1-Day Value at Risk ($)', max_digits=18, null=True)),
                ('expected_shortfall', models.DecimalField(blank=True, decimal_places=4, help_text='Conditional VaR (CVaR)', max_digits=18, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('volatility_annualized', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='PortfolioManagement.portfolio')),
            ],
            options={
                'ordering': ['-calculation_date'],
                'unique_together': {('portfolio', 'calculation_date')},
            },
        ),
    ]
