# Generated by Django 6.1.1 on 2026-09-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retrying')], default='PENDING', max_length=20)),
                ('runtime_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('server_type', models.CharField(choices=[('APP', 'Application Server (Django/Gunicorn)'), ('DB', 'Database Server (PostgreSQL)'), ('CACHE', 'Cache / Broker (Redis)'), ('WORKER', 'Asynchronous Task Worker (Celery)')], default='APP', max_length=20)),
                ('status', models.CharField(choices=[('ONLINE', 'Online / Healthy'), ('DEGRADED', 'Degraded Performance'), ('OFFLINE', 'Offline / Critical'), ('MAINTENANCE', 'Under Maintenance')], default='ONLINE', max_length=20)),
                ('cpu_usage_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('memory_usage_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_ping', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value (String, JSON, or Boolean)')),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Minor Degradation'), ('MEDIUM', 'Partial Outage'), ('HIGH', 'Major Outage'), ('CRITICAL', 'Critical System Failure')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('IDENTIFIED', 'Problem Identified'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='ITSystems.systemserver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
